name: json_serializable_immutable

packages:
  - builders/**
  - combine_example/*
  - typehelpers/**

scripts:
  test: 
    run: |
      # FIXME: https://github.com/dart-lang/sdk/issues/45307
      melos exec -- flutter test --no-pub
    select-package:
      dir-exists:
        - test

  build_runner:
    run: |
      # FIXME: https://github.com/invertase/melos/issues/117
      melos exec -c 1 -- \
        "dart pub global run build_runner build --delete-conflicting-outputs"
    select-package:
      depends-on: 'build_runner'

  analyze:
    run: melos exec -- dart analyze .

  postbootstrap:
    run: dart pub global activate build_runner
