name: json_serializable_immutable

packages:
  - builders/**
  - combine_example/*
  - typehelpers/**

scripts:
  test:
    run: |
      # FIXME: https://github.com/dart-lang/sdk/issues/45307
      melos exec -- flutter test --no-pub
    packageFilters:
      dirExists:
        - test

  build_runner:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"

  analyze:
    run: melos exec -- dart analyze .

  postbootstrap:
    run: dart pub global activate build_runner
